### ISSUE TITLE
GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed One element could not be created. Exiting.

### ISSUE THREAD

**Issue by zhaowuyao** [NVIDIA-AI-IOT/redaction_with_deepstream#1]
when run
./deepstream-redaction-app -c configs/pgie_config_fd_lpd.txt -i sample_videos/sample_output.mp4 
GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed
One element could not be created.  Exiting.
what can i do?thax

**Comment by wkelongws** [comment]
Hi Wuyao,

Can you confirm that you can run the samples in DeepStream SDK 3.0 to make sure the SDK has been installed correctly? (Described in the "Installing Pre-requisites" section)

**Comment by wkelongws** [comment]
Now we have updated the app to be compatible with DS 4.0. It should work on all nvidia platforms (tested on DGPU, Jetson Xavier and Jetson Nano) as well as work in containers. And you now have an option to use usb webcam as input.
