### ISSUE TITLE
Error in make: fatal error: gst/video/video.h: No such file or directory (solved)

### ISSUE THREAD

**Issue by jinli-ece-cs** [NVIDIA-AI-IOT/redaction_with_deepstream#3]
I am using the NGC container _nvcr.io/nvidia/deepstream:3.0-18.11_, and encountered the following error 
```
root@d828b86d0d86:~/DeepStream_Release/sources/apps/redaction_with_deepstream# make
cc -I../../includes `pkg-config --cflags gstreamer-1.0`   -c -o deepstream_redaction_app.o deepstream_redaction_app.c
In file included from deepstream_redaction_app.c:26:0:
../../includes/gstnvdsmeta.h:59:29: fatal error: gst/video/video.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'deepstream_redaction_app.o' failed
make: *** [deepstream_redaction_app.o] Error 1

```

I searched for a while and found that installing this additional package solves the problem.
`apt-get install libgstreamer-plugins-base1.0-dev`

**Comment by wkelongws** [comment]
Great thanks jinli. Now we have updated the app to be compatible with DS 4.0. It should work on all nvidia platforms (tested on DGPU, Jetson Xavier and Jetson Nano) as well as work in containers. And you now have an option to use usb webcam as input.
