### ISSUE TITLE
model for jetson nano

### ISSUE THREAD

**Issue by bobogumizelka** [NVIDIA-AI-IOT/redaction_with_deepstream#4]
Is there a possibility to run this app on jetson nano? How can I obtain/prepare the proper model?

**Comment by wkelongws** [comment]
Hi the app runs on Jetson nano as well. 
1. $ cd <path-to-deepstream-sdk>/sources/apps
2. $ git clone https://github.com/NVIDIA-AI-IOT/redaction_with_deepstream.git
3. $ cd redaction_with_deepstream 
4. $ make
5. run the app. If you have a usb web cam connected to your nano you can quickly test by runnning:
    $ ./deepstream-redaction-app -c configs/pgie_config_fd_lpd.txt
    it will bring up the webcam on screen and redact faces/license plates in it.

**Comment by hgnan** [comment]
I am having some trouble at compile 
`jetson@jetson-nano:~/nas/deepstream/redaction_with_deepstream$ make        
cc -c -o deepstream_redaction_app.o -DPLATFORM_TEGRA -I ../../includes `pkg-config --cflags gstreamer-1.0` deepstream_redaction_app.c
deepstream_redaction_app.c:27:10: fatal error: gstnvdsmeta.h: No such file or directory
 #include "gstnvdsmeta.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
Makefile:53: recipe for target 'deepstream_redaction_app.o' failed
make: *** [deepstream_redaction_app.o] Error 1`

I have installed DS4 and my jetson_release as blow
` - NVIDIA Jetson NANO/TX1
   * Jetpack 4.2.1 [L4T 32.2.0]
   * CUDA GPU architecture 5.3
 - Libraries:
   * CUDA 10.0.326
   * cuDNN 7.5.0.56-1+cuda10.0
   * TensorRT 5.1.6.1-1+cuda10.0
   * Visionworks 1.6.0.500n
   * OpenCV 4.1.0 compiled CUDA: YES
 - Jetson Performance: inactive`

How to fix it？
